### ISSUE TITLE
Graphs 

### ISSUE THREAD

**Issue by MaryamMghz** [debsourav33/INF502-Project-Github-Mining#5]
A boxplot that compares closed vs. open pull requests in terms of number of commits 
A boxplot that compares closed vs. open pull requests in terms of additions and deletions 
A boxplot that compares the number of changed files grouped by the author association 
A scatterplot that shows the relationship between additions and deletions 
Calculate the correlation between all the numeric data in the pull requests for a repository Create and store visual representation data about all the repositories (via pandas): A line graph showing the total number of pull requests per day
A line graph comparing number of open and closed pull requests per day 
A bars plot comparing the number of users per repository

**Comment by mrshammari** [comment]
All of them done

Boxplots for Closed . Open Pull Requests

Boxplot for Changed Files Groups by author association.

Scatterplot for Additions v Deletions: Shows their relationship.

Correlation &Visual Representations,all repositories, including line &bar graphs.
